# Generated by Django 5.0.1 on 2026-01-27 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('type', models.CharField(choices=[('maintenance', 'Технические работы'), ('update', 'Обновление'), ('news', 'Новость'), ('warning', 'Предупреждение'), ('info', 'Информация')], default='info', max_length=20, verbose_name='тип уведомления')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли это уведомление пользователям', verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='создано пользователем')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='закрыто')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='дата прочтения')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата закрытия')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='notifications.notification', verbose_name='уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'статус уведомления',
                'verbose_name_plural': 'статусы уведомлений',
                'ordering': ['-notification__created_at'],
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
