# Generated by Django 5.0.1 on 2026-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='posts/attachments/%Y/%m/%d/', verbose_name='файл')),
                ('file_type', models.CharField(choices=[('audio', 'Аудио'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='тип файла')),
                ('file_name', models.CharField(max_length=255, verbose_name='название файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='размер файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
            ],
            options={
                'verbose_name': 'вложение поста',
                'verbose_name_plural': 'вложения постов',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/%Y/%m/%d/', verbose_name='изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
            ],
            options={
                'verbose_name': 'изображение поста',
                'verbose_name_plural': 'изображения постов',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
