# Generated by Django 5.0.1 on 2026-01-25 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('reason', models.TextField(help_text='Расскажите немного о себе и почему хотите присоединиться к блогу', max_length=500, verbose_name='почему хотите присоединиться')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='возраст')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='род деятельности')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата подачи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата обработки')),
                ('admin_comment', models.TextField(blank=True, help_text='Причина отклонения или заметки', verbose_name='комментарий администратора')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='обработана пользователем')),
            ],
            options={
                'verbose_name': 'заявка на регистрацию',
                'verbose_name_plural': 'заявки на регистрацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
