# Generated by Django 5.0.1 on 2026-01-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='код подтверждения email'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='email_verification_code_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время создания кода'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email подтвержден'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('pending_email', 'Ожидает подтверждения email'), ('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending_email', max_length=20, verbose_name='статус'),
        ),
    ]
