# Generated by Django 5.0.1 on 2026-01-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registrationrequest_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Получать уведомления на email о публикации новых постов', verbose_name='email уведомления о новых постах'),
        ),
    ]
